2022-06-10 17:44:18,034 - root - INFO - InfiniemBot Iniciado...
2022-06-10 18:16:47,891 - root - INFO - InfiniemBot Iniciado...
2022-06-10 18:16:47,892 - apscheduler.scheduler - INFO - Scheduler started
2022-06-10 18:18:35,772 - __main__ - WARNING - [UPDATE] "{'message': {'voice': {'file_id': 'AwACAgEAAxkBAAIBCWKjtS--LKUYQH__bIts6lmdr53DAAJ9AgAClKEhRRcNUmQDvOyGJAQ', 'mime_type': 'audio/ogg', 'duration': 2, 'file_size': 10520, 'file_unique_id': 'AgADfQIAApShIUU'}, 'delete_chat_photo': False, 'entities': [], 'chat': {'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'type': 'private', 'id': 509436549}, 'photo': [], 'date': 1654895919, 'message_id': 265, 'group_chat_created': False, 'new_chat_members': [], 'channel_chat_created': False, 'new_chat_photo': [], 'caption_entities': [], 'supergroup_chat_created': False, 'from': {'language_code': 'es', 'is_bot': False, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549}}, 'update_id': 642605125}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-10 19:19:39,973 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-10 19:19:39,973 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-10 19:19:42,441 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-10 19:19:46,219 - root - INFO - InfiniemBot Iniciado...
2022-06-10 19:19:46,221 - apscheduler.scheduler - INFO - Scheduler started
2022-06-10 19:20:01,097 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-10 19:20:38,779 - __main__ - WARNING - [UPDATE] "{'message': {'delete_chat_photo': False, 'new_chat_photo': [], 'photo': [], 'entities': [], 'date': 1654899644, 'message_id': 270, 'chat': {'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private', 'username': 'NahuelPassano'}, 'voice': {'file_id': 'AwACAgEAAxkBAAIBDmKjw7x6fS6vWu9gdVqtvoM-aviWAAJ_AgAClKEhRb8gGo4MZIOoJAQ', 'file_size': 9876, 'mime_type': 'audio/ogg', 'duration': 2, 'file_unique_id': 'AgADfwIAApShIUU'}, 'caption_entities': [], 'group_chat_created': False, 'supergroup_chat_created': False, 'new_chat_members': [], 'channel_chat_created': False, 'from': {'is_bot': False, 'username': 'NahuelPassano', 'language_code': 'es', 'last_name': 'Passano', 'first_name': 'Nahuel', 'id': 509436549}}, 'update_id': 642605127}" causa del error "[Errno 2] No such file or directory: 'audios/509436549---10-06-2022---19-20-38.wav'"
2022-06-10 19:20:52,595 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-10 19:20:52,596 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-10 19:20:53,506 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-10 19:20:56,697 - root - INFO - InfiniemBot Iniciado...
2022-06-10 19:20:56,698 - apscheduler.scheduler - INFO - Scheduler started
2022-06-10 19:21:20,888 - __main__ - WARNING - [UPDATE] "{'update_id': 642605128, 'message': {'photo': [], 'supergroup_chat_created': False, 'voice': {'file_size': 13021, 'duration': 2, 'file_id': 'AwACAgEAAxkBAAIBD2Kjw-WWokur9SoCRovNosbgjeEVAAKAAgAClKEhRaVfKlNERf57JAQ', 'mime_type': 'audio/ogg', 'file_unique_id': 'AgADgAIAApShIUU'}, 'new_chat_members': [], 'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'channel_chat_created': False, 'group_chat_created': False, 'delete_chat_photo': False, 'new_chat_photo': [], 'message_id': 271, 'date': 1654899685, 'entities': [], 'caption_entities': [], 'from': {'last_name': 'Passano', 'id': 509436549, 'first_name': 'Nahuel', 'is_bot': False, 'username': 'NahuelPassano', 'language_code': 'es'}}}" causa del error "[Errno 2] No such file or directory: 'audios/509436549---10-06-2022---19-21-20.wav'"
2022-06-10 19:21:49,107 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-10 19:21:49,111 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-10 19:21:50,190 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-10 19:21:53,274 - root - INFO - InfiniemBot Iniciado...
2022-06-10 19:21:53,275 - apscheduler.scheduler - INFO - Scheduler started
2022-06-10 19:22:00,346 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'entities': [], 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'type': 'private', 'first_name': 'Nahuel', 'last_name': 'Passano', 'username': 'NahuelPassano', 'id': 509436549}, 'supergroup_chat_created': False, 'channel_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_unique_id': 'AgADgQIAApShIUU', 'file_id': 'AwACAgEAAxkBAAIBEGKjxAwCMPGlVh2PhodQPoJWK_NrAAKBAgAClKEhRR8MBZAQH2OVJAQ', 'file_size': 10955, 'duration': 2}, 'message_id': 272, 'photo': [], 'date': 1654899724, 'from': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False, 'id': 509436549, 'language_code': 'es', 'last_name': 'Passano'}}, 'update_id': 642605129}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-10 19:25:06,619 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'entities': [], 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'type': 'private', 'first_name': 'Nahuel', 'last_name': 'Passano', 'username': 'NahuelPassano', 'id': 509436549}, 'supergroup_chat_created': False, 'channel_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_unique_id': 'AgADggIAApShIUU', 'file_id': 'AwACAgEAAxkBAAIBEmKjxMcFWQoKGDODqTTfOFVIBzK2AAKCAgAClKEhRaCNOC0Q5cqFJAQ', 'file_size': 11488, 'duration': 2}, 'message_id': 274, 'photo': [], 'date': 1654899911, 'from': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False, 'id': 509436549, 'language_code': 'es', 'last_name': 'Passano'}}, 'update_id': 642605130}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-10 19:28:00,291 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-10 19:28:08,453 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-10 19:34:49,037 - root - INFO - [NEW ACCESS] chat_id : 1111391978 - firstname : Fran - lastname : None - username Franciscorv9
2022-06-10 19:35:02,262 - __main__ - INFO - [UPDATE] Usuario Fran envió un audio
2022-06-10 19:35:21,027 - __main__ - INFO - [UPDATE] Usuario Fran envió un audio
2022-06-10 19:36:06,068 - __main__ - INFO - [UPDATE] Usuario Fran consume el servicio /sensores 🌡
2022-06-10 19:36:41,828 - __main__ - INFO - [UPDATE] Usuario Fran consume el servicio /acciones 💡
2022-06-10 19:37:00,376 - __main__ - INFO - [UPDATE] Usuario Fran consume el servicio /sensores 🌡
2022-06-10 19:37:04,870 - __main__ - INFO - [UPDATE] Usuario Fran consume el servicio /acciones 💡
2022-06-10 19:37:08,251 - __main__ - INFO - [UPDATE] Usuario Fran consume el servicio /buscar 🔎
2022-06-10 19:59:46,470 - root - INFO - InfiniemBot Iniciado...
2022-06-10 19:59:46,471 - apscheduler.scheduler - INFO - Scheduler started
2022-06-10 20:51:50,256 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-10 20:51:50,261 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 17:05:35,231 - root - INFO - InfiniemBot Iniciado...
2022-06-11 17:05:35,233 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 17:05:38,229 - __main__ - WARNING - [UPDATE] "{'update_id': 642605155, 'message': {'caption_entities': [], 'new_chat_members': [], 'entities': [], 'new_chat_photo': [], 'date': 1654919665, 'message_id': 328, 'photo': [], 'delete_chat_photo': False, 'chat': {'type': 'private', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano'}, 'supergroup_chat_created': False, 'group_chat_created': False, 'channel_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_size': 10204, 'duration': 2, 'file_id': 'AwACAgEAAxkBAAIBSGKkEfGzVgABAv99fGQiNB-M_lRVgQACzgIAAv44IUU-PSyt0iAFcSQE', 'file_unique_id': 'AgADzgIAAv44IUU'}, 'from': {'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-11 17:05:38,230 - __main__ - INFO - [UPDATE] Usuario Nahuel consume el servicio /buscar 🔎
2022-06-11 17:05:38,646 - __main__ - INFO - [UPDATE] Usuario Nahuel consume el servicio /sensores 🌡
2022-06-11 17:05:40,069 - __main__ - WARNING - [UPDATE] "{'update_id': 642605158, 'message': {'caption_entities': [], 'new_chat_members': [], 'entities': [], 'new_chat_photo': [], 'date': 1654977653, 'message_id': 331, 'photo': [], 'delete_chat_photo': False, 'chat': {'type': 'private', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano'}, 'supergroup_chat_created': False, 'group_chat_created': False, 'channel_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_size': 8873, 'duration': 1, 'file_id': 'AwACAgEAAxkBAAIBS2Kk9HWpt2oVLLxVn7Tjh4SFfy2AAAI7AwAC_jgpRcOYM3GVDYZaJAQ', 'file_unique_id': 'AgADOwMAAv44KUU'}, 'from': {'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-11 17:05:40,069 - __main__ - INFO - [UPDATE] Usuario Nahuel consume el servicio /buscar 🔎
2022-06-11 17:05:58,396 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 17:05:58,396 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 17:06:00,569 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 17:30:22,736 - root - INFO - InfiniemBot Iniciado...
2022-06-11 17:30:22,737 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 17:31:00,857 - __main__ - INFO - [UPDATE] Usuario Nahuel consume el servicio /sensores 🌡
2022-06-11 17:36:12,551 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 17:36:12,552 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 17:36:13,891 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 17:38:05,557 - root - INFO - InfiniemBot Iniciado...
2022-06-11 17:38:05,558 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 17:41:05,201 - __main__ - INFO - [UPDATE] Usuario Nahuel consume el servicio /sensores 🌡
2022-06-11 17:41:09,597 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 17:41:09,597 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 17:41:10,603 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 21:12:54,854 - root - INFO - InfiniemBot Iniciado...
2022-06-11 21:12:54,855 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 21:13:00,402 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:00,402 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:13:06,397 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:06,397 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:13:13,642 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:13,642 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:13:19,766 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:19,767 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:13:28,701 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:28,702 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:13:41,860 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:13:41,860 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:14:01,350 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:14:01,350 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:14:34,802 - __main__ - WARNING - [UPDATE] "{'update_id': 642605175, 'message': {'delete_chat_photo': False, 'voice': {'duration': 4, 'file_unique_id': 'AgADZAMAAv44KUU', 'file_size': 29366, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBcGKlL-fJo0n_pcHog3C4dB9rDpPiAAJkAwAC_jgpRZeu9x5RGgABTiQE'}, 'chat': {'type': 'private', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549}, 'caption_entities': [], 'new_chat_members': [], 'supergroup_chat_created': False, 'photo': [], 'group_chat_created': False, 'message_id': 368, 'date': 1654992871, 'new_chat_photo': [], 'entities': [], 'channel_chat_created': False, 'from': {'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549}}}" causa del error "join() takes exactly one argument (2 given)"
2022-06-11 21:14:48,992 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:14:48,993 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:15:31,962 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:15:31,962 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:15:44,580 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 21:15:44,581 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 21:15:46,834 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 21:15:48,947 - root - INFO - InfiniemBot Iniciado...
2022-06-11 21:15:48,948 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 21:15:59,180 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'entities': [], 'message_id': 370, 'date': 1654992956, 'channel_chat_created': False, 'voice': {'duration': 2, 'file_unique_id': 'AgADZQMAAv44KUU', 'file_id': 'AwACAgEAAxkBAAIBcmKlMDzybi1Q1ZqcMmORKb8CnOsrAAJlAwAC_jgpRV5YB7wic2iqJAQ', 'file_size': 16252, 'mime_type': 'audio/ogg'}, 'new_chat_members': [], 'delete_chat_photo': False, 'chat': {'username': 'NahuelPassano', 'type': 'private', 'id': 509436549, 'first_name': 'Nahuel', 'last_name': 'Passano'}, 'supergroup_chat_created': False, 'photo': [], 'group_chat_created': False, 'new_chat_photo': [], 'from': {'last_name': 'Passano', 'is_bot': False, 'username': 'NahuelPassano', 'language_code': 'es', 'id': 509436549, 'first_name': 'Nahuel'}}, 'update_id': 642605176}" causa del error "join() takes exactly one argument (2 given)"
2022-06-11 21:16:06,502 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:16:06,503 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:16:41,061 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:16:41,064 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:17:15,582 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:17:15,583 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:17:50,120 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:17:50,121 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:18:21,401 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 21:18:21,402 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 21:19:47,910 - root - INFO - InfiniemBot Iniciado...
2022-06-11 21:19:47,911 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 21:19:53,579 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:19:53,579 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:19:59,589 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:19:59,590 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:20:05,610 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:20:05,610 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:20:12,862 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:20:12,862 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:20:22,001 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:20:22,001 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:20:30,956 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:20:30,957 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:20:44,134 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:20:44,134 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:21:00,046 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:21:00,046 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:21:17,541 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:21:17,541 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:21:47,708 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:21:47,710 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:07,626 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 21:22:07,627 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 21:22:09,805 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 21:22:11,449 - root - INFO - InfiniemBot Iniciado...
2022-06-11 21:22:11,450 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 21:22:16,985 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:16,985 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:21,089 - __main__ - WARNING - [UPDATE] "{'update_id': 642605178, 'message': {'supergroup_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'voice': {'file_unique_id': 'AgADZwMAAv44KUU', 'mime_type': 'audio/ogg', 'file_size': 13594, 'duration': 3, 'file_id': 'AwACAgEAAxkBAAIBdmKlMbqfnjDBrr3xqv6o_zdsJ6ouAAJnAwAC_jgpRdZfiohugZPOJAQ'}, 'entities': [], 'new_chat_photo': [], 'date': 1654993338, 'message_id': 374, 'delete_chat_photo': False, 'group_chat_created': False, 'chat': {'type': 'private', 'id': 509436549, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano'}, 'channel_chat_created': False, 'photo': [], 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'id': 509436549, 'first_name': 'Nahuel', 'last_name': 'Passano'}}}" causa del error "join() takes exactly one argument (2 given)"
2022-06-11 21:22:22,982 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:22,982 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:29,736 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:29,737 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:33,730 - __main__ - WARNING - [UPDATE] "{'update_id': 642605179, 'message': {'supergroup_chat_created': False, 'caption_entities': [], 'new_chat_members': [], 'voice': {'file_unique_id': 'AgADaAMAAv44KUU', 'mime_type': 'audio/ogg', 'file_size': 14433, 'duration': 2, 'file_id': 'AwACAgEAAxkBAAIBeGKlMceBrCJ00jDcm6eaEKIKxWvNAAJoAwAC_jgpRURfVI5Hin65JAQ'}, 'entities': [], 'new_chat_photo': [], 'date': 1654993351, 'message_id': 376, 'delete_chat_photo': False, 'group_chat_created': False, 'chat': {'type': 'private', 'id': 509436549, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano'}, 'channel_chat_created': False, 'photo': [], 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'id': 509436549, 'first_name': 'Nahuel', 'last_name': 'Passano'}}}" causa del error "join() takes exactly one argument (2 given)"
2022-06-11 21:22:35,117 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:35,118 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:44,681 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:44,681 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:22:57,282 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:22:57,283 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:23:13,185 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:23:13,186 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:23:15,698 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-11 21:23:15,698 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-11 21:23:17,140 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-11 21:23:18,670 - root - INFO - InfiniemBot Iniciado...
2022-06-11 21:23:18,671 - apscheduler.scheduler - INFO - Scheduler started
2022-06-11 21:23:26,634 - __main__ - WARNING - [UPDATE] "{'message': {'voice': {'file_unique_id': 'AgADaQMAAv44KUU', 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBemKlMfwRXijtiI7S4OOMAzynDEVjAAJpAwAC_jgpRSpDSbRYkqMCJAQ', 'duration': 2, 'file_size': 10625}, 'channel_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'last_name': 'Passano', 'type': 'private'}, 'date': 1654993404, 'new_chat_members': [], 'photo': [], 'new_chat_photo': [], 'supergroup_chat_created': False, 'message_id': 378, 'group_chat_created': False, 'caption_entities': [], 'from': {'first_name': 'Nahuel', 'is_bot': False, 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'language_code': 'es'}}, 'update_id': 642605180}" causa del error "No connection adapters were found for 'localhost:8000/get-response-from-audio/'"
2022-06-11 21:23:34,794 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:23:34,795 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:24:04,964 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:24:04,965 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:24:47,958 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:24:47,958 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:25:22,494 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:25:22,495 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:25:57,030 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:25:57,031 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:26:31,562 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:26:31,563 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:27:06,093 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:27:06,093 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:27:40,598 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:27:40,599 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:28:15,136 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:28:15,136 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:28:49,676 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:28:49,677 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:29:24,217 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:29:24,218 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:29:58,752 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:29:58,753 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-11 21:30:33,294 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-11 21:30:33,294 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 11:36:55,925 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:36:55,927 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:37:54,963 - __main__ - WARNING - [UPDATE] "{'message': {'message_id': 383, 'caption_entities': [], 'photo': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'type': 'private', 'last_name': 'Passano'}, 'supergroup_chat_created': False, 'new_chat_photo': [], 'delete_chat_photo': False, 'new_chat_members': [], 'entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'voice': {'duration': 2, 'file_unique_id': 'AgAD2gEAAm1wQUU', 'file_size': 13132, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBf2KnS8H4okvjoMrBfrQTV6NSlf22AALaAQACbXBBRfutIPNVvh4jJAQ'}, 'date': 1655131073, 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'id': 509436549, 'last_name': 'Passano', 'first_name': 'Nahuel'}}, 'update_id': 642605182}" causa del error "No connection adapters were found for 'localhost:8000/get-response-from-audio/'"
2022-06-13 11:40:41,104 - __main__ - WARNING - [UPDATE] "{'message': {'message_id': 386, 'caption_entities': [], 'photo': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'type': 'private', 'last_name': 'Passano'}, 'supergroup_chat_created': False, 'new_chat_photo': [], 'delete_chat_photo': False, 'new_chat_members': [], 'entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'voice': {'duration': 2, 'file_unique_id': 'AgAD2wEAAm1wQUU', 'file_size': 12589, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBgmKnTGeINm1iTkRoij7vxCkMxthmAALbAQACbXBBRZHgxi2EJER0JAQ'}, 'date': 1655131239, 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'id': 509436549, 'last_name': 'Passano', 'first_name': 'Nahuel'}}, 'update_id': 642605183}" causa del error "No connection adapters were found for 'localhost:8000/get-response-from-audio/'"
2022-06-13 11:41:29,505 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:41:29,505 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:41:30,388 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:41:31,794 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:41:31,795 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:42:18,159 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:42:18,160 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:42:18,743 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:42:19,851 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:42:19,852 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:42:30,615 - __main__ - WARNING - [UPDATE] "{'update_id': 642605184, 'message': {'new_chat_photo': [], 'channel_chat_created': False, 'date': 1655131348, 'delete_chat_photo': False, 'message_id': 389, 'photo': [], 'new_chat_members': [], 'supergroup_chat_created': False, 'entities': [], 'caption_entities': [], 'chat': {'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private', 'username': 'NahuelPassano'}, 'group_chat_created': False, 'voice': {'file_size': 14475, 'file_id': 'AwACAgEAAxkBAAIBhWKnTNP9sE70eguH5fbZy36DltCFAALcAQACbXBBRb5wlT73J2OCJAQ', 'file_unique_id': 'AgAD3AEAAm1wQUU', 'mime_type': 'audio/ogg', 'duration': 2}, 'from': {'language_code': 'es', 'id': 509436549, 'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano'}}}" causa del error "No connection adapters were found for 'localhost:8000/get-response-from-audio/'"
2022-06-13 11:43:20,998 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:43:20,998 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:43:21,844 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:43:23,071 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:43:23,072 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:43:30,248 - __main__ - WARNING - [UPDATE] "{'message': {'photo': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'type': 'private', 'last_name': 'Passano'}, 'new_chat_photo': [], 'channel_chat_created': False, 'supergroup_chat_created': False, 'new_chat_members': [], 'voice': {'duration': 1, 'file_unique_id': 'AgAD3QEAAm1wQUU', 'file_id': 'AwACAgEAAxkBAAIBiGKnTRBI-X4xW3ENns5rvSyD2b_ZAALdAQACbXBBRQ4e_vbvz2_kJAQ', 'mime_type': 'audio/ogg', 'file_size': 11573}, 'group_chat_created': False, 'delete_chat_photo': False, 'caption_entities': [], 'entities': [], 'date': 1655131408, 'message_id': 392, 'from': {'id': 509436549, 'is_bot': False, 'first_name': 'Nahuel', 'last_name': 'Passano', 'username': 'NahuelPassano', 'language_code': 'es'}}, 'update_id': 642605185}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:44:17,585 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:44:17,585 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:44:18,152 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:44:19,824 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:44:19,825 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:44:26,477 - __main__ - WARNING - [UPDATE] "{'message': {'chat': {'username': 'NahuelPassano', 'id': 509436549, 'last_name': 'Passano', 'type': 'private', 'first_name': 'Nahuel'}, 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIBi2KnTUhZ3UWxN0HPHjWf21DFP3dSAALfAQACbXBBRZUl_joPcv9rJAQ', 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD3wEAAm1wQUU', 'duration': 1, 'file_size': 5982}, 'channel_chat_created': False, 'supergroup_chat_created': False, 'date': 1655131464, 'new_chat_members': [], 'new_chat_photo': [], 'group_chat_created': False, 'entities': [], 'caption_entities': [], 'message_id': 395, 'delete_chat_photo': False, 'from': {'last_name': 'Passano', 'language_code': 'es', 'username': 'NahuelPassano', 'id': 509436549, 'is_bot': False, 'first_name': 'Nahuel'}}, 'update_id': 642605186}" causa del error "No connection adapters were found for '127.0.0.1:8000'"
2022-06-13 11:44:55,476 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:44:55,476 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:44:55,922 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:44:57,158 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:44:57,159 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:45:43,156 - __main__ - WARNING - [UPDATE] "{'update_id': 642605187, 'message': {'voice': {'file_id': 'AwACAgEAAxkBAAIBjmKnTZTyQ3T3-tbgAAHbg3wMe3UiewAC4AEAAm1wQUV-LCV1yuFNISQE', 'mime_type': 'audio/ogg', 'file_size': 14402, 'duration': 2, 'file_unique_id': 'AgAD4AEAAm1wQUU'}, 'supergroup_chat_created': False, 'message_id': 398, 'channel_chat_created': False, 'group_chat_created': False, 'entities': [], 'caption_entities': [], 'photo': [], 'delete_chat_photo': False, 'date': 1655131541, 'new_chat_members': [], 'chat': {'type': 'private', 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'first_name': 'Nahuel'}, 'new_chat_photo': [], 'from': {'is_bot': False, 'language_code': 'es', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:46:32,778 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:46:32,778 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:46:33,270 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:46:34,756 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:46:34,757 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:46:41,542 - __main__ - WARNING - [UPDATE] "{'message': {'new_chat_members': [], 'date': 1655131599, 'voice': {'file_unique_id': 'AgAD4QEAAm1wQUU', 'file_size': 10289, 'file_id': 'AwACAgEAAxkBAAIBkWKnTc9MgDlZaLOPfsHAvaLVU-itAALhAQACbXBBRcfLyLU4L7i0JAQ', 'mime_type': 'audio/ogg', 'duration': 1}, 'entities': [], 'caption_entities': [], 'chat': {'username': 'NahuelPassano', 'last_name': 'Passano', 'first_name': 'Nahuel', 'type': 'private', 'id': 509436549}, 'group_chat_created': False, 'channel_chat_created': False, 'photo': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'message_id': 401, 'supergroup_chat_created': False, 'from': {'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'language_code': 'es', 'last_name': 'Passano'}}, 'update_id': 642605188}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:47:54,970 - __main__ - WARNING - [UPDATE] "{'message': {'new_chat_members': [], 'date': 1655131673, 'voice': {'file_unique_id': 'AgAD4gEAAm1wQUU', 'file_size': 13562, 'file_id': 'AwACAgEAAxkBAAIBlGKnThmEr-_zUEbepoPv79e_7gJ6AALiAQACbXBBRfoVATamDKwbJAQ', 'mime_type': 'audio/ogg', 'duration': 2}, 'entities': [], 'caption_entities': [], 'chat': {'username': 'NahuelPassano', 'last_name': 'Passano', 'first_name': 'Nahuel', 'type': 'private', 'id': 509436549}, 'group_chat_created': False, 'channel_chat_created': False, 'photo': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'message_id': 404, 'supergroup_chat_created': False, 'from': {'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549, 'language_code': 'es', 'last_name': 'Passano'}}, 'update_id': 642605189}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:50:39,626 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:50:39,627 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:50:40,115 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:50:41,331 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:50:41,333 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:50:52,385 - __main__ - WARNING - [UPDATE] "{'update_id': 642605190, 'message': {'message_id': 407, 'group_chat_created': False, 'new_chat_photo': [], 'date': 1655131850, 'caption_entities': [], 'channel_chat_created': False, 'delete_chat_photo': False, 'chat': {'id': 509436549, 'last_name': 'Passano', 'type': 'private', 'first_name': 'Nahuel', 'username': 'NahuelPassano'}, 'entities': [], 'new_chat_members': [], 'voice': {'duration': 1, 'file_id': 'AwACAgEAAxkBAAIBl2KnTsrm1RLZMB_WBSmg8gSxUenXAALjAQACbXBBRRu6SsVBoPqnJAQ', 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD4wEAAm1wQUU', 'file_size': 6487}, 'supergroup_chat_created': False, 'photo': [], 'from': {'first_name': 'Nahuel', 'id': 509436549, 'language_code': 'es', 'is_bot': False, 'last_name': 'Passano', 'username': 'NahuelPassano'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:54:02,532 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:54:02,532 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:54:03,179 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:54:04,396 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:54:04,397 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:54:29,996 - __main__ - WARNING - [UPDATE] "{'update_id': 642605191, 'message': {'voice': {'duration': 1, 'file_id': 'AwACAgEAAxkBAAIBmmKnT6PDwd48R96FZOR0zoPnmoZfAALkAQACbXBBReKvJyVCrsp0JAQ', 'file_size': 12109, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD5AEAAm1wQUU'}, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'type': 'private', 'last_name': 'Passano', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549}, 'entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'message_id': 410, 'channel_chat_created': False, 'photo': [], 'supergroup_chat_created': False, 'date': 1655132067, 'from': {'id': 509436549, 'last_name': 'Passano', 'language_code': 'es', 'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:54:38,571 - __main__ - WARNING - [UPDATE] "{'update_id': 642605192, 'message': {'voice': {'duration': 1, 'file_id': 'AwACAgEAAxkBAAIBnWKnT62gKfTMu3V_vNFFO7c_C9yhAALlAQACbXBBRYU8qwdvBkFQJAQ', 'file_size': 9426, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD5QEAAm1wQUU'}, 'group_chat_created': False, 'new_chat_photo': [], 'chat': {'type': 'private', 'last_name': 'Passano', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549}, 'entities': [], 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'message_id': 413, 'channel_chat_created': False, 'photo': [], 'supergroup_chat_created': False, 'date': 1655132077, 'from': {'id': 509436549, 'last_name': 'Passano', 'language_code': 'es', 'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:55:06,945 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:55:06,945 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:55:07,404 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 11:55:08,319 - root - INFO - InfiniemBot Iniciado...
2022-06-13 11:55:08,320 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 11:55:19,324 - __main__ - WARNING - [UPDATE] "{'message': {'voice': {'file_size': 11549, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD5gEAAm1wQUU', 'duration': 2, 'file_id': 'AwACAgEAAxkBAAIBoGKnT9VmZk__cnFAlTI-3fpaMHfZAALmAQACbXBBRV0XuwkhB_iZJAQ'}, 'entities': [], 'new_chat_members': [], 'channel_chat_created': False, 'date': 1655132117, 'message_id': 416, 'photo': [], 'delete_chat_photo': False, 'caption_entities': [], 'group_chat_created': False, 'supergroup_chat_created': False, 'chat': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private'}, 'new_chat_photo': [], 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'id': 509436549, 'last_name': 'Passano', 'first_name': 'Nahuel'}}, 'update_id': 642605193}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 11:58:16,422 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 11:58:16,422 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 11:58:17,112 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:00:40,732 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:00:40,736 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:00:49,521 - __main__ - WARNING - [UPDATE] "{'update_id': 642605194, 'message': {'new_chat_members': [], 'new_chat_photo': [], 'entities': [], 'channel_chat_created': False, 'voice': {'duration': 2, 'file_size': 17347, 'file_id': 'AwACAgEAAxkBAAIBo2KnUR9Mu41cSc3hV2QmEGnQX6T2AALnAQACbXBBReYFc5NhmhfNJAQ', 'file_unique_id': 'AgAD5wEAAm1wQUU', 'mime_type': 'audio/ogg'}, 'photo': [], 'delete_chat_photo': False, 'supergroup_chat_created': False, 'message_id': 419, 'group_chat_created': False, 'caption_entities': [], 'date': 1655132447, 'chat': {'type': 'private', 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'first_name': 'Nahuel'}, 'from': {'first_name': 'Nahuel', 'language_code': 'es', 'last_name': 'Passano', 'is_bot': False, 'id': 509436549, 'username': 'NahuelPassano'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:01:05,472 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:01:05,475 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:02:59,176 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'date': 1655132472, 'message_id': 422, 'new_chat_members': [], 'supergroup_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBpmKnUTd04sI8rxLfejBVkAtDXy50AALoAQACbXBBRZlM3rhONBWVJAQ', 'file_unique_id': 'AgAD6AEAAm1wQUU', 'duration': 2, 'file_size': 10388}, 'delete_chat_photo': False, 'chat': {'first_name': 'Nahuel', 'type': 'private', 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549}, 'new_chat_photo': [], 'entities': [], 'group_chat_created': False, 'channel_chat_created': False, 'photo': [], 'from': {'username': 'NahuelPassano', 'language_code': 'es', 'is_bot': False, 'first_name': 'Nahuel', 'last_name': 'Passano', 'id': 509436549}}, 'update_id': 642605195}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:07:30,059 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:07:30,060 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:13:31,234 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 12:13:31,234 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 12:13:32,001 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:13:34,285 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:13:34,286 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:14:23,464 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 12:14:23,464 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 12:14:24,019 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:14:25,793 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:14:25,794 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:14:36,266 - __main__ - WARNING - [UPDATE] "{'update_id': 642605196, 'message': {'entities': [], 'new_chat_photo': [], 'date': 1655133274, 'channel_chat_created': False, 'photo': [], 'supergroup_chat_created': False, 'chat': {'last_name': 'Passano', 'username': 'NahuelPassano', 'type': 'private', 'first_name': 'Nahuel', 'id': 509436549}, 'new_chat_members': [], 'voice': {'file_unique_id': 'AgAD6QEAAm1wQUU', 'duration': 1, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAIBqWKnVFqqm_y_7DKy61qHFDf0eGf-AALpAQACbXBBRTmKOFXHp9vpJAQ', 'file_size': 9374}, 'delete_chat_photo': False, 'group_chat_created': False, 'caption_entities': [], 'message_id': 425, 'from': {'is_bot': False, 'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'language_code': 'es', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:15:05,373 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 12:15:05,373 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 12:15:05,847 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:15:07,089 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:15:07,090 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:15:21,072 - __main__ - WARNING - [UPDATE] "{'update_id': 642605197, 'message': {'supergroup_chat_created': False, 'entities': [], 'photo': [], 'chat': {'first_name': 'Nahuel', 'last_name': 'Passano', 'type': 'private', 'username': 'NahuelPassano', 'id': 509436549}, 'caption_entities': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'new_chat_members': [], 'date': 1655133319, 'message_id': 427, 'group_chat_created': False, 'voice': {'mime_type': 'audio/ogg', 'file_size': 19005, 'file_id': 'AwACAgEAAxkBAAIBq2KnVIcex5us9V_tgDfc6NolnKAkAALqAQACbXBBRbpRKHTTyCdeJAQ', 'file_unique_id': 'AgAD6gEAAm1wQUU', 'duration': 3}, 'channel_chat_created': False, 'from': {'last_name': 'Passano', 'language_code': 'es', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549, 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:25:18,139 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f298ace5880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /bot5320155453:AAGK7Ikurpk-DOPM-5BA-Z-sjPNYhAOKJTM/getUpdates
2022-06-13 12:25:35,562 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 12:25:35,563 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 12:25:36,170 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:26:02,890 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:26:02,891 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:26:34,097 - root - INFO - [NEW ACCESS] chat_id : 509436549 - firstname : Nahuel - lastname : Passano - username NahuelPassano
2022-06-13 12:30:58,389 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 12:30:58,389 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 12:30:58,919 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 12:31:00,170 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:31:00,171 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:33:26,738 - root - INFO - InfiniemBot Iniciado...
2022-06-13 12:33:26,739 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 12:34:05,450 - __main__ - WARNING - [UPDATE] "{'update_id': 642605211, 'message': {'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIBx2KnWOutr4hcclwlvldE_9hDfr7HAALxAQACbXBBRTB3VtAUZOv8JAQ', 'mime_type': 'audio/ogg', 'file_size': 15994, 'duration': 2, 'file_unique_id': 'AgAD8QEAAm1wQUU'}, 'message_id': 455, 'supergroup_chat_created': False, 'entities': [], 'group_chat_created': False, 'date': 1655134443, 'new_chat_photo': [], 'channel_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:40:55,015 - __main__ - WARNING - [UPDATE] "{'update_id': 642605213, 'message': {'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIBy2KnWoVbCfZVowNnQutfZMv1Tw_bAALyAQACbXBBRSvOwsBedR-rJAQ', 'mime_type': 'audio/ogg', 'file_size': 13360, 'duration': 2, 'file_unique_id': 'AgAD8gEAAm1wQUU'}, 'message_id': 459, 'supergroup_chat_created': False, 'entities': [], 'group_chat_created': False, 'date': 1655134853, 'new_chat_photo': [], 'channel_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:43:04,472 - __main__ - WARNING - [UPDATE] "{'update_id': 642605214, 'message': {'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIBzWKnWwcfjgqzHxY5QDXqJaVQ1fjJAALzAQACbXBBRd7Rrlqi-75HJAQ', 'mime_type': 'audio/ogg', 'file_size': 11293, 'duration': 1, 'file_unique_id': 'AgAD8wEAAm1wQUU'}, 'message_id': 461, 'supergroup_chat_created': False, 'entities': [], 'group_chat_created': False, 'date': 1655134983, 'new_chat_photo': [], 'channel_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:56:46,105 - __main__ - WARNING - [UPDATE] "{'update_id': 642605215, 'message': {'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIBz2KnXjxsuW7eKEr9olWWjLXeGg0NAAL5AQACbXBBRaMWzT2NP38TJAQ', 'mime_type': 'audio/ogg', 'file_size': 12336, 'duration': 2, 'file_unique_id': 'AgAD-QEAAm1wQUU'}, 'message_id': 463, 'supergroup_chat_created': False, 'entities': [], 'group_chat_created': False, 'date': 1655135804, 'new_chat_photo': [], 'channel_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 12:57:34,244 - __main__ - WARNING - [UPDATE] "{'update_id': 642605216, 'message': {'chat': {'id': 509436549, 'type': 'private', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}, 'new_chat_members': [], 'delete_chat_photo': False, 'caption_entities': [], 'photo': [], 'voice': {'file_id': 'AwACAgEAAxkBAAIB0WKnXmzn_innnnW-JR25Yiz8106QAAL6AQACbXBBRbgBDwUEuGf1JAQ', 'mime_type': 'audio/ogg', 'file_size': 19979, 'duration': 3, 'file_unique_id': 'AgAD-gEAAm1wQUU'}, 'message_id': 465, 'supergroup_chat_created': False, 'entities': [], 'group_chat_created': False, 'date': 1655135852, 'new_chat_photo': [], 'channel_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:03:39,749 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:03:39,750 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:03:40,165 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:03:41,412 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:03:41,413 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:03:42,996 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:03:42,996 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:03:45,553 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:03:46,887 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:03:46,888 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:04:07,627 - __main__ - WARNING - [UPDATE] "{'message': {'message_id': 467, 'caption_entities': [], 'channel_chat_created': False, 'chat': {'type': 'private', 'last_name': 'Passano', 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'id': 509436549}, 'voice': {'duration': 1, 'file_id': 'AwACAgEAAxkBAAIB02KnX_VRz-zsRv23FitFiOanFGKOAAL7AQACbXBBRdGB0XrzKQ0eJAQ', 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD-wEAAm1wQUU', 'file_size': 11154}, 'supergroup_chat_created': False, 'delete_chat_photo': False, 'new_chat_photo': [], 'new_chat_members': [], 'date': 1655136245, 'photo': [], 'entities': [], 'group_chat_created': False, 'from': {'language_code': 'es', 'id': 509436549, 'first_name': 'Nahuel', 'is_bot': False, 'username': 'NahuelPassano', 'last_name': 'Passano'}}, 'update_id': 642605217}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:05:38,887 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:05:38,889 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:05:39,585 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:05:41,036 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:05:41,037 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:05:51,493 - __main__ - WARNING - [UPDATE] "{'message': {'group_chat_created': False, 'caption_entities': [], 'chat': {'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'first_name': 'Nahuel', 'id': 509436549}, 'delete_chat_photo': False, 'voice': {'file_id': 'AwACAgEAAxkBAAIB1WKnYF0XnbuerH18uWBcU0xqDnbqAAL8AQACbXBBRQi_t_Pmpc8XJAQ', 'mime_type': 'audio/ogg', 'file_size': 7778, 'duration': 1, 'file_unique_id': 'AgAD_AEAAm1wQUU'}, 'message_id': 469, 'new_chat_members': [], 'photo': [], 'channel_chat_created': False, 'date': 1655136349, 'entities': [], 'new_chat_photo': [], 'supergroup_chat_created': False, 'from': {'last_name': 'Passano', 'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'language_code': 'es', 'id': 509436549}}, 'update_id': 642605218}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:06:03,570 - __main__ - WARNING - [UPDATE] "{'message': {'group_chat_created': False, 'caption_entities': [], 'chat': {'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'first_name': 'Nahuel', 'id': 509436549}, 'delete_chat_photo': False, 'voice': {'file_id': 'AwACAgEAAxkBAAIB12KnYGoShj697U8Lb1gKs-cHuZZMAAL9AQACbXBBRX1P3jF5K0gfJAQ', 'mime_type': 'audio/ogg', 'file_size': 9454, 'duration': 1, 'file_unique_id': 'AgAD_QEAAm1wQUU'}, 'message_id': 471, 'new_chat_members': [], 'photo': [], 'channel_chat_created': False, 'date': 1655136362, 'entities': [], 'new_chat_photo': [], 'supergroup_chat_created': False, 'from': {'last_name': 'Passano', 'is_bot': False, 'first_name': 'Nahuel', 'username': 'NahuelPassano', 'language_code': 'es', 'id': 509436549}}, 'update_id': 642605219}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:10:53,860 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:10:53,860 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:10:54,889 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:10:56,422 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:10:56,422 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:11:25,143 - __main__ - WARNING - [UPDATE] "{'update_id': 642605220, 'message': {'supergroup_chat_created': False, 'chat': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private'}, 'date': 1655136681, 'channel_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'photo': [], 'message_id': 473, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'caption_entities': [], 'voice': {'file_size': 12612, 'duration': 1, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD_wEAAm1wQUU', 'file_id': 'AwACAgEAAxkBAAIB2WKnYanYwqklfdU8mK54wg098hPIAAL_AQACbXBBRXKl3_r7E3qfJAQ'}, 'from': {'id': 509436549, 'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:11:26,256 - __main__ - WARNING - [UPDATE] "{'update_id': 642605221, 'message': {'supergroup_chat_created': False, 'chat': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private'}, 'date': 1655136681, 'channel_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'photo': [], 'message_id': 474, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'caption_entities': [], 'voice': {'file_size': 10525, 'duration': 1, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAD_gEAAm1wQUU', 'file_id': 'AwACAgEAAxkBAAIB2mKnYalnb3d7we_F1rOH46bRjrhhAAL-AQACbXBBRcT0LT5198XXJAQ'}, 'from': {'id': 509436549, 'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:21:21,775 - __main__ - WARNING - [UPDATE] "{'update_id': 642605222, 'message': {'supergroup_chat_created': False, 'chat': {'username': 'NahuelPassano', 'first_name': 'Nahuel', 'id': 509436549, 'last_name': 'Passano', 'type': 'private'}, 'date': 1655137280, 'channel_chat_created': False, 'delete_chat_photo': False, 'entities': [], 'photo': [], 'message_id': 477, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'caption_entities': [], 'voice': {'file_size': 11683, 'duration': 1, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgAEAgACbXBBRQ', 'file_id': 'AwACAgEAAxkBAAIB3WKnZAABeav9lb8OEKk52Q2ffbGFOQADAgACbXBBRSlq3k0IZmjdJAQ'}, 'from': {'id': 509436549, 'is_bot': False, 'language_code': 'es', 'last_name': 'Passano', 'username': 'NahuelPassano', 'first_name': 'Nahuel'}}}" causa del error "No connection adapters were found for '127.0.0.1:8000/get-response-from-audio/'"
2022-06-13 13:25:27,152 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:25:27,155 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:25:27,959 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:25:29,862 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:25:29,864 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:25:39,011 - __main__ - WARNING - [UPDATE] "{'update_id': 642605223, 'message': {'entities': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'type': 'private', 'last_name': 'Passano', 'id': 509436549}, 'group_chat_created': False, 'voice': {'file_id': 'AwACAgEAAxkBAAIB32KnZQFQQ-nK8u1-0MZS32nWHSlKAAICAgACbXBBRZtMaF3yxTeJJAQ', 'file_size': 6500, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgADAgIAAm1wQUU', 'duration': 0}, 'caption_entities': [], 'delete_chat_photo': False, 'photo': [], 'new_chat_members': [], 'supergroup_chat_created': False, 'message_id': 479, 'channel_chat_created': False, 'new_chat_photo': [], 'date': 1655137537, 'from': {'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'language_code': 'es', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "'Prediction'"
2022-06-13 13:26:54,753 - __main__ - WARNING - [UPDATE] "{'update_id': 642605224, 'message': {'entities': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'type': 'private', 'last_name': 'Passano', 'id': 509436549}, 'group_chat_created': False, 'voice': {'file_id': 'AwACAgEAAxkBAAIB4WKnZUm1whDpdztto3FNuZuHJQ9XAAIDAgACbXBBRRiAo4BjKXUAASQE', 'file_size': 18836, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgADAwIAAm1wQUU', 'duration': 2}, 'caption_entities': [], 'delete_chat_photo': False, 'photo': [], 'new_chat_members': [], 'supergroup_chat_created': False, 'message_id': 481, 'channel_chat_created': False, 'new_chat_photo': [], 'date': 1655137609, 'from': {'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'language_code': 'es', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "Timed out"
2022-06-13 13:27:31,273 - __main__ - WARNING - [UPDATE] "{'update_id': 642605225, 'message': {'entities': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'type': 'private', 'last_name': 'Passano', 'id': 509436549}, 'group_chat_created': False, 'voice': {'file_id': 'AwACAgEAAxkBAAIB4mKnZW14Vm2j0hDtQkiyUQbyFf6dAAIEAgACbXBBRei1ck77tQWDJAQ', 'file_size': 19990, 'mime_type': 'audio/ogg', 'file_unique_id': 'AgADBAIAAm1wQUU', 'duration': 3}, 'caption_entities': [], 'delete_chat_photo': False, 'photo': [], 'new_chat_members': [], 'supergroup_chat_created': False, 'message_id': 482, 'channel_chat_created': False, 'new_chat_photo': [], 'date': 1655137645, 'from': {'username': 'NahuelPassano', 'last_name': 'Passano', 'id': 509436549, 'language_code': 'es', 'first_name': 'Nahuel', 'is_bot': False}}}" causa del error "'Prediction'"
2022-06-13 13:36:46,591 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:36:46,593 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:36:47,713 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:41:10,794 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:41:10,795 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:41:50,747 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 13:45:26,413 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:45:26,416 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:45:27,947 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:27,948 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:32,248 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:32,250 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:33,508 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:33,508 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:39,070 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:39,070 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:40,919 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:41,593 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 13:45:42,570 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:45,253 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:45,254 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:47,818 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:47,818 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:52,723 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:52,723 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:45:56,418 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:45:56,419 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:01,941 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:01,942 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:07,267 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:07,268 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:11,632 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:11,632 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:19,492 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:19,494 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:24,890 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:29,140 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:29,140 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:37,002 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:41,282 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:41,283 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:46:52,942 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:57,239 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:46:57,241 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:47:14,706 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:47:14,707 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:47:40,617 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:47:44,955 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:47:44,955 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:48:23,674 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:48:27,962 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2022-06-13 13:48:27,962 - __main__ - WARNING - [UPDATE] "None" causa del error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2022-06-13 13:49:19,065 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:49:19,066 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:49:54,670 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 13:50:09,668 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 13:50:39,615 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 13:54:46,123 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 13:54:46,124 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 13:54:47,098 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 13:54:48,273 - root - INFO - InfiniemBot Iniciado...
2022-06-13 13:54:48,274 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 13:58:10,182 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 14:05:29,074 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 14:11:59,367 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 14:12:45,289 - __main__ - INFO - [UPDATE] Usuario Santiago envió un audio
2022-06-13 14:13:22,672 - __main__ - INFO - [UPDATE] Usuario Fran envió un audio
2022-06-13 14:13:44,765 - __main__ - INFO - [UPDATE] Usuario Fran envió un audio
2022-06-13 14:18:00,321 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 14:18:00,322 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 21:04:22,184 - root - INFO - InfiniemBot Iniciado...
2022-06-13 21:04:22,185 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 21:04:39,221 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'voice': {'duration': 2, 'file_unique_id': 'AgADWgIAAm1wQUU', 'file_size': 18848, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAICF2Kn0JV3zfnYL5BV7681kml1WwEIAAJaAgACbXBBRdpSvlAfbQgZJAQ'}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'id': 509436549}, 'channel_chat_created': False, 'date': 1655165077, 'message_id': 535, 'from': {'first_name': 'Nahuel', 'last_name': 'Passano', 'language_code': 'es', 'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False}}, 'update_id': 642605250}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-13 21:05:04,370 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'voice': {'duration': 2, 'file_unique_id': 'AgADWwIAAm1wQUU', 'file_size': 19439, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAICGWKn0K89xO8D8kAxTRQcO9Yco2-mAAJbAgACbXBBRQNDyT04ozdNJAQ'}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'id': 509436549}, 'channel_chat_created': False, 'date': 1655165103, 'message_id': 537, 'from': {'first_name': 'Nahuel', 'last_name': 'Passano', 'language_code': 'es', 'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False}}, 'update_id': 642605251}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-13 21:06:04,557 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'voice': {'duration': 2, 'file_unique_id': 'AgADXAIAAm1wQUU', 'file_size': 14410, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAICG2Kn0Ot9iuOWbzNlv4lBycOD7bzUAAJcAgACbXBBRcv3cLiz_Yj3JAQ'}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'id': 509436549}, 'channel_chat_created': False, 'date': 1655165163, 'message_id': 539, 'from': {'first_name': 'Nahuel', 'last_name': 'Passano', 'language_code': 'es', 'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False}}, 'update_id': 642605252}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-13 21:06:44,717 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'voice': {'duration': 2, 'file_unique_id': 'AgADXQIAAm1wQUU', 'file_size': 14986, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAICHWKn0RNaSo3dStaUmeixqEuFUllhAAJdAgACbXBBRdh6woav23KmJAQ'}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'id': 509436549}, 'channel_chat_created': False, 'date': 1655165203, 'message_id': 541, 'from': {'first_name': 'Nahuel', 'last_name': 'Passano', 'language_code': 'es', 'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False}}, 'update_id': 642605253}" causa del error "Expecting value: line 1 column 1 (char 0)"
2022-06-13 21:07:01,193 - __main__ - WARNING - [UPDATE] "{'message': {'caption_entities': [], 'supergroup_chat_created': False, 'entities': [], 'photo': [], 'voice': {'duration': 2, 'file_unique_id': 'AgADXgIAAm1wQUU', 'file_size': 18814, 'mime_type': 'audio/ogg', 'file_id': 'AwACAgEAAxkBAAICH2Kn0SMxtht4tKrBIaAkdUsVodw7AAJeAgACbXBBRUdbefOop8-0JAQ'}, 'delete_chat_photo': False, 'group_chat_created': False, 'new_chat_photo': [], 'new_chat_members': [], 'chat': {'first_name': 'Nahuel', 'username': 'NahuelPassano', 'last_name': 'Passano', 'type': 'private', 'id': 509436549}, 'channel_chat_created': False, 'date': 1655165219, 'message_id': 543, 'from': {'first_name': 'Nahuel', 'last_name': 'Passano', 'language_code': 'es', 'id': 509436549, 'username': 'NahuelPassano', 'is_bot': False}}, 'update_id': 642605254}" causa del error "'Prediction'"
2022-06-13 21:08:54,446 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 21:08:54,447 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 21:08:55,251 - telegram.ext.updater - WARNING - Exiting immediately!
2022-06-13 21:08:56,910 - root - INFO - InfiniemBot Iniciado...
2022-06-13 21:08:56,911 - apscheduler.scheduler - INFO - Scheduler started
2022-06-13 21:09:06,299 - __main__ - INFO - [UPDATE] Usuario Nahuel envió un audio
2022-06-13 21:09:26,771 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2022-06-13 21:09:26,772 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-06-13 21:09:27,545 - telegram.ext.updater - WARNING - Exiting immediately!
